apiVersion: v1
kind: Service
metadata:
  name: nginx-multitool-nodeport
spec:
  type: NodePort
  selector:
    app: nginx-multitool
  ports:
    - name: nginx
      port: 80
      targetPort: 80
      nodePort: 30080
